name: camera_with_rtmp_example
description: Demonstrates how to use the rtmppublisher plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera_with_rtmp:
    path: ../

  path_provider: ^1.6.8
  cupertino_icons: ^0.1.3
  video_player: ^0.10.11
  e2e: ^0.4.2
  wakelock: ^0.1.4+1
  cached_network_image: ^2.0.0
  flutter_custom_clippers: ^1.1.0
  font_awesome_flutter: ^8.8.1
  dio: ^3.0.9
  flutter_vlc_player: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true